VENV 	= .venv
SQLDIR  = db
PYTHON 	= $(VENV)/Scripts/python
PIP 	= $(VENV)/Scripts/pip
DB		= psql
DBNAME  = removals
SYSPYTHON = py

run: $(VENV)\Scripts\activate
	PYTHONDONTWRITEBYTECODE=1 $(PYTHON) main.py

$(VENV)\Scripts\activate: requirements.txt
	@command -v $(SYSPYTHON) -v > /dev/null || (echo "Error: `python3` not found on your system." && exit 1)
	$(SYSPYTHON) -m venv $(VENV)
	$(PIP) install -r requirements.txt

clean:
	rm -rf __pycache__
	rm -rf $(VENV)

clean-db:
	$(DB) -f $(SQLDIR)/migrations/99-drop_schema.sql -d $(DBNAME) --username=postgres

init-db:
	$(DB) -f $(SQLDIR)/migrations/0-schema.sql -d $(DBNAME) --username=postgres

.PHONY: run clean