CREATE TRIGGER TRG_BidActions__modify
BEFORE INSERT OR UPDATE ON BidActions
FOR EACH ROW
EXECUTE FUNCTION bid_modify();

CREATE TRIGGER TRG_Items__update
BEFORE UPDATE ON Items
FOR EACH ROW
EXECUTE FUNCTION item_update();

CREATE TRIGGER TRG_Orders__update
BEFORE UPDATE ON Orders
FOR EACH ROW
EXECUTE FUNCTION order_update();

CREATE TRIGGER TRG_Orders__insert
BEFORE INSERT ON Orders
FOR EACH ROW
EXECUTE FUNCTION order_insert();

CREATE TRIGGER TRG_Users__update
BEFORE UPDATE ON Users
FOR EACH ROW
EXECUTE FUNCTION user_update();

CREATE TRIGGER TRG_Users__before_insert
BEFORE INSERT ON Users
FOR EACH ROW
EXECUTE FUNCTION user_before_insert();