INSERT INTO Countries (country_code, country_name)
VALUES
  ('AF', 'Afghanistan'),
  ('AL', 'Albania'),
  ('DZ', 'Algeria'),
  ('AD', 'Andorra'),
  ('AO', 'Angola'),
  ('AR', 'Argentina'),
  ('AM', 'Armenia'),
  ('AU', 'Australia'),
  ('AT', 'Austria'),
  ('AZ', 'Azerbaijan'),
  ('BS', 'Bahamas'),
  ('BH', 'Bahrain'),
  ('BD', 'Bangladesh'),
  ('BY', 'Belarus'),
  ('BE', 'Belgium'),
  ('BZ', 'Belize'),
  ('BJ', 'Benin'),
  ('BT', 'Bhutan'),
  ('BO', 'Bolivia'),
  ('BA', 'Bosnia and Herzegovina'),
  ('BW', 'Botswana'),
  ('BR', 'Brazil'),
  ('BN', 'Brunei'),
  ('BG', 'Bulgaria'),
  ('BF', 'Burkina Faso'),
  ('BI', 'Burundi'),
  ('KH', 'Cambodia'),
  ('CM', 'Cameroon'),
  ('CA', 'Canada'),
  ('CV', 'Cape Verde'),
  ('CF', 'Central African Republic'),
  ('TD', 'Chad'),
  ('CL', 'Chile'),
  ('CN', 'China'),
  ('CO', 'Colombia'),
  ('KM', 'Comoros'),
  ('CD', 'Congo (DRC)'),
  ('CG', 'Congo (Republic)'),
  ('CR', 'Costa Rica'),
  ('HR', 'Croatia'),
  ('CU', 'Cuba'),
  ('CY', 'Cyprus'),
  ('CZ', 'Czech Republic'),
  ('DK', 'Denmark'),
  ('DJ', 'Djibouti'),
  ('DO', 'Dominican Republic'),
  ('EC', 'Ecuador'),
  ('EG', 'Egypt'),
  ('SV', 'El Salvador'),
  ('EE', 'Estonia'),
  ('ET', 'Ethiopia'),
  ('FJ', 'Fiji'),
  ('FI', 'Finland'),
  ('FR', 'France'),
  ('GA', 'Gabon'),
  ('GM', 'Gambia'),
  ('GE', 'Georgia'),
  ('DE', 'Germany'),
  ('GH', 'Ghana'),
  ('GR', 'Greece'),
  ('GT', 'Guatemala'),
  ('GN', 'Guinea'),
  ('GW', 'Guinea-Bissau'),
  ('GY', 'Guyana'),
  ('HT', 'Haiti'),
  ('HN', 'Honduras'),
  ('HU', 'Hungary'),
  ('IS', 'Iceland'),
  ('IN', 'India'),
  ('ID', 'Indonesia'),
  ('IR', 'Iran'),
  ('IQ', 'Iraq'),
  ('IE', 'Ireland'),
  ('IL', 'Israel'),
  ('IT', 'Italy'),
  ('JM', 'Jamaica'),
  ('JP', 'Japan'),
  ('JO', 'Jordan'),
  ('KZ', 'Kazakhstan'),
  ('KE', 'Kenya'),
  ('KP', 'North Korea'),
  ('KR', 'South Korea'),
  ('KW', 'Kuwait'),
  ('KG', 'Kyrgyzstan'),
  ('LA', 'Laos'),
  ('LV', 'Latvia'),
  ('LB', 'Lebanon'),
  ('LS', 'Lesotho'),
  ('LR', 'Liberia'),
  ('LY', 'Libya'),
  ('LT', 'Lithuania'),
  ('LU', 'Luxembourg'),
  ('MG', 'Madagascar'),
  ('MW', 'Malawi'),
  ('MY', 'Malaysia'),
  ('MV', 'Maldives'),
  ('ML', 'Mali'),
  ('MT', 'Malta'),
  ('MR', 'Mauritania'),
  ('MU', 'Mauritius'),
  ('MX', 'Mexico'),
  ('MD', 'Moldova'),
  ('MC', 'Monaco'),
  ('MN', 'Mongolia'),
  ('ME', 'Montenegro'),
  ('MA', 'Morocco'),
  ('MZ', 'Mozambique'),
  ('MM', 'Myanmar'),
  ('NA', 'Namibia'),
  ('NP', 'Nepal'),
  ('NL', 'Netherlands'),
  ('NZ', 'New Zealand'),
  ('NI', 'Nicaragua'),
  ('NE', 'Niger'),
  ('NG', 'Nigeria'),
  ('NO', 'Norway'),
  ('OM', 'Oman'),
  ('PK', 'Pakistan'),
  ('PA', 'Panama'),
  ('PG', 'Papua New Guinea'),
  ('PY', 'Paraguay'),
  ('PE', 'Peru'),
  ('PH', 'Philippines'),
  ('PL', 'Poland'),
  ('PT', 'Portugal'),
  ('QA', 'Qatar'),
  ('RO', 'Romania'),
  ('RU', 'Russia'),
  ('RW', 'Rwanda'),
  ('SA', 'Saudi Arabia'),
  ('SN', 'Senegal'),
  ('RS', 'Serbia'),
  ('SC', 'Seychelles'),
  ('SL', 'Sierra Leone'),
  ('SG', 'Singapore'),
  ('SK', 'Slovakia'),
  ('SI', 'Slovenia'),
  ('SO', 'Somalia'),
  ('ZA', 'South Africa'),
  ('ES', 'Spain'),
  ('LK', 'Sri Lanka'),
  ('SD', 'Sudan'),
  ('SR', 'Suriname'),
  ('SZ', 'Swaziland'),
  ('SE', 'Sweden'),
  ('CH', 'Switzerland'),
  ('SY', 'Syria'),
  ('TJ', 'Tajikistan'),
  ('TZ', 'Tanzania'),
  ('TH', 'Thailand'),
  ('TG', 'Togo'),
  ('TT', 'Trinidad and Tobago'),
  ('TN', 'Tunisia'),
  ('TR', 'Turkey'),
  ('TM', 'Turkmenistan'),
  ('UG', 'Uganda'),
  ('UA', 'Ukraine'),
  ('AE', 'United Arab Emirates'),
  ('GB', 'United Kingdom'),
  ('US', 'United States'),
  ('UY', 'Uruguay'),
  ('UZ', 'Uzbekistan'),
  ('VE', 'Venezuela'),
  ('VN', 'Vietnam'),
  ('YE', 'Yemen'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabwe')
ON CONFLICT DO NOTHING;

INSERT INTO Counties (country_id, county_name)
SELECT country_id, county_name
FROM Countries
CROSS JOIN (
    VALUES
    ('n/a'),
    ('Bedfordshire'),
    ('Berkshire'),
    ('Buckinghamshire'),
    ('Cambridgeshire'),
    ('Cheshire'),
    ('Cornwall'),
    ('Cumberland'),
    ('Derbyshire'),
    ('Devon'),
    ('Dorset'),
    ('Durham'),
    ('Essex'),
    ('Gloucestershire'),
    ('Hampshire'),
    ('Herefordshire'),
    ('Hertfordshire'),
    ('Huntingdonshire'),
    ('Kent'),
    ('Lancashire'),
    ('Leicestershire'),
    ('Lincolnshire'),
    ('Middlesex'),
    ('Norfolk'),
    ('Northamptonshire'),
    ('Northumberland'),
    ('Nottinghamshire'),
    ('Oxfordshire'),
    ('Rutland'),
    ('Shropshire'),
    ('Somerset'),
    ('Staffordshire'),
    ('Suffolk'),
    ('Surrey'),
    ('Sussex'),
    ('Warwickshire'),
    ('Westmorland'),
    ('Wiltshire'),
    ('Worcestershire'),
    ('Yorkshire'),
    
    -- Historic Counties of Wales
    ('Anglesey'),
    ('Brecknockshire'),
    ('Caernarfonshire'),
    ('Cardiganshire'),
    ('Carmarthenshire'),
    ('Denbighshire'),
    ('Flintshire'),
    ('Glamorgan'),
    ('Merionethshire'),
    ('Monmouthshire'),
    ('Montgomeryshire'),
    ('Pembrokeshire'),
    ('Radnorshire'),

    -- Historic Counties of Scotland
    ('Aberdeenshire'),
    ('Angus'),
    ('Argyll'),
    ('Ayrshire'),
    ('Banffshire'),
    ('Berwickshire'),
    ('Bute'),
    ('Caithness'),
    ('Clackmannanshire'),
    ('Dumfriesshire'),
    ('Dunbartonshire'),
    ('East Lothian'),
    ('Fife'),
    ('Inverness-shire'),
    ('Kincardineshire'),
    ('Kinross-shire'),
    ('Kirkcudbrightshire'),
    ('Lanarkshire'),
    ('Midlothian'),
    ('Moray'),
    ('Nairnshire'),
    ('Orkney'),
    ('Peeblesshire'),
    ('Perthshire'),
    ('Renfrewshire'),
    ('Ross-shire'),
    ('Roxburghshire'),
    ('Selkirkshire'),
    ('Shetland'),
    ('Stirlingshire'),
    ('Sutherland'),
    ('West Lothian'),
    ('Wigtownshire'),

    -- Historic Counties of Ireland
    ('Antrim'),
    ('Armagh'),
    ('Carlow'),
    ('Cavan'),
    ('Clare'),
    ('Cork'),
    ('Donegal'),
    ('Down'),
    ('Dublin'),
    ('Fermanagh'),
    ('Galway'),
    ('Kerry'),
    ('Kildare'),
    ('Kilkenny'),
    ('Laois'),
    ('Leitrim'),
    ('Limerick'),
    ('Londonderry'),
    ('Longford'),
    ('Louth'),
    ('Mayo'),
    ('Meath'),
    ('Monaghan'),
    ('Offaly'),
    ('Roscommon'),
    ('Sligo'),
    ('Tipperary'),
    ('Tyrone'),
    ('Waterford'),
    ('Westmeath'),
    ('Wexford'),
    ('Wicklow')
) AS historic_counties(county_name)
WHERE Countries.country_code = 'GB'
ON CONFLICT DO NOTHING;

INSERT INTO Cities (city_name, county_id)
SELECT city_name, Counties.county_id
FROM Counties
CROSS JOIN (
    -- England
    VALUES
    ('London', 'Middlesex'),
    ('Westminster', 'Middlesex'),
    ('Camden', 'Middlesex'),
    ('Greenwich', 'Middlesex'),
    ('Manchester', 'Lancashire'),
    ('Liverpool', 'Lancashire'),
    ('Preston', 'Lancashire'),
    ('Blackpool', 'Lancashire'),
    ('Birmingham', 'Warwickshire'),
    ('Coventry', 'Warwickshire'),
    ('Leeds', 'Yorkshire'),
    ('Sheffield', 'Yorkshire'),
    ('York', 'Yorkshire'),
    ('Bradford', 'Yorkshire'),
    ('Hull', 'Yorkshire'),
    ('Newcastle upon Tyne', 'Northumberland'),
    ('Bristol', 'Gloucestershire'),
    ('Gloucester', 'Gloucestershire'),
    ('Nottingham', 'Nottinghamshire'),
    ('Leicester', 'Leicestershire'),
    ('Derby', 'Derbyshire'),
    ('Plymouth', 'Devon'),
    ('Exeter', 'Devon'),
    ('Torquay', 'Devon'),
    ('Southampton', 'Hampshire'),
    ('Portsmouth', 'Hampshire'),
    ('Winchester', 'Hampshire'),
    ('Brighton', 'Sussex'),
    ('Hastings', 'Sussex'),
    ('Canterbury', 'Kent'),
    ('Maidstone', 'Kent'),
    ('Dover', 'Kent'),
    ('Norwich', 'Norfolk'),
    ('Ipswich', 'Suffolk'),
    ('Cambridge', 'Cambridgeshire'),
    ('Peterborough', 'Cambridgeshire'),
    ('Oxford', 'Oxfordshire'),
    ('Reading', 'Berkshire'),
    ('Slough', 'Berkshire'),
    ('Luton', 'Bedfordshire'),
    ('Bedford', 'Bedfordshire'),
    ('Chelmsford', 'Essex'),
    ('Southend-on-Sea', 'Essex'),
    ('Colchester', 'Essex'),
    ('Stoke-on-Trent', 'Staffordshire'),
    ('Wolverhampton', 'Staffordshire'),
    ('Chester', 'Cheshire'),
    ('Warrington', 'Cheshire'),
    ('Truro', 'Cornwall'),
    ('Plymouth', 'Devon'),
    ('Bath', 'Somerset'),
    ('Taunton', 'Somerset'),
    ('Shrewsbury', 'Shropshire'),
    ('Telford', 'Shropshire'),
    ('Salisbury', 'Wiltshire'),
    ('Swindon', 'Wiltshire'),
    ('Worcester', 'Worcestershire'),
    ('Hereford', 'Herefordshire'),
    ('Lincoln', 'Lincolnshire'),
    ('Grimsby', 'Lincolnshire'),
    ('Northampton', 'Northamptonshire'),
    ('Bournemouth', 'Dorset'),
    ('Poole', 'Dorset'),
    ('Dorchester', 'Dorset'),
    ('Carlisle', 'Cumberland'),
    ('Sunderland', 'Durham'),
    ('Durham', 'Durham'),
    ('Darlington', 'Durham'),
    
    -- Wales
    ('Cardiff', 'Glamorgan'),
    ('Swansea', 'Glamorgan'),
    ('Newport', 'Monmouthshire'),
    ('Wrexham', 'Denbighshire'),
    ('Bangor', 'Caernarfonshire'),
    ('Aberystwyth', 'Cardiganshire'),
    ('Carmarthen', 'Carmarthenshire'),
    ('Mold', 'Flintshire'),
    ('Brecon', 'Brecknockshire'),
    ('Welshpool', 'Montgomeryshire'),
    ('Haverfordwest', 'Pembrokeshire'),
    ('Prestatyn', 'Flintshire'),
    ('Llandrindod Wells', 'Radnorshire'),
    ('Holyhead', 'Anglesey'),
    ('Dolgellau', 'Merionethshire'),
    
    -- Scotland
    ('Edinburgh', 'Midlothian'),
    ('Glasgow', 'Lanarkshire'),
    ('Aberdeen', 'Aberdeenshire'),
    ('Dundee', 'Angus'),
    ('Stirling', 'Stirlingshire'),
    ('Perth', 'Perthshire'),
    ('Inverness', 'Inverness-shire'),
    ('Ayr', 'Ayrshire'),
    ('Dumfries', 'Dumfriesshire'),
    ('Kirkcudbright', 'Kirkcudbrightshire'),
    ('Paisley', 'Renfrewshire'),
    ('Falkirk', 'Stirlingshire'),
    ('Motherwell', 'Lanarkshire'),
    ('Hamilton', 'Lanarkshire'),
    ('Kilmarnock', 'Ayrshire'),
    ('Greenock', 'Renfrewshire'),
    ('Dunfermline', 'Fife'),
    ('Kirkcaldy', 'Fife'),
    ('Oban', 'Argyll'),
    ('Fort William', 'Inverness-shire'),
    ('Wick', 'Caithness'),
    ('Thurso', 'Caithness'),
    ('Lerwick', 'Shetland'),
    ('Kirkwall', 'Orkney'),
    ('Peebles', 'Peeblesshire'),
    ('Selkirk', 'Selkirkshire'),
    ('Jedburgh', 'Roxburghshire'),
    ('Berwick-upon-Tweed', 'Berwickshire'),
    ('Banff', 'Banffshire'),
    ('Elgin', 'Moray'),
    ('Nairn', 'Nairnshire'),
    ('Dornoch', 'Sutherland'),
    ('Stonehaven', 'Kincardineshire'),
    ('Kinross', 'Kinross-shire'),
    ('Alloa', 'Clackmannanshire'),
    ('Rothesay', 'Bute'),
    ('Stranraer', 'Wigtownshire'),
    ('Haddington', 'East Lothian'),
    ('Linlithgow', 'West Lothian'),
    
    -- Ireland
    ('Dublin', 'Dublin'),
    ('Cork', 'Cork'),
    ('Limerick', 'Limerick'),
    ('Galway', 'Galway'),
    ('Waterford', 'Waterford'),
    ('Drogheda', 'Louth'),
    ('Dundalk', 'Louth'),
    ('Swords', 'Dublin'),
    ('Bray', 'Wicklow'),
    ('Navan', 'Meath'),
    ('Ennis', 'Clare'),
    ('Kilkenny', 'Kilkenny'),
    ('Carlow', 'Carlow'),
    ('Naas', 'Kildare'),
    ('Portlaoise', 'Laois'),
    ('Tullamore', 'Offaly'),
    ('Athlone', 'Westmeath'),
    ('Mullingar', 'Westmeath'),
    ('Longford', 'Longford'),
    ('Roscommon', 'Roscommon'),
    ('Castlebar', 'Mayo'),
    ('Sligo', 'Sligo'),
    ('Letterkenny', 'Donegal'),
    ('Monaghan', 'Monaghan'),
    ('Cavan', 'Cavan'),
    ('Carrick-on-Shannon', 'Leitrim'),
    ('Tralee', 'Kerry'),
    ('Killarney', 'Kerry'),
    ('Clonmel', 'Tipperary'),
    ('Thurles', 'Tipperary'),
    ('Wexford', 'Wexford'),
    ('Arklow', 'Wicklow'),
    ('Belfast', 'Antrim'),
    ('Lisburn', 'Antrim'),
    ('Newtownabbey', 'Antrim'),
    ('Bangor', 'Down'),
    ('Newry', 'Down'),
    ('Craigavon', 'Armagh'),
    ('Armagh', 'Armagh'),
    ('Omagh', 'Tyrone'),
    ('Dungannon', 'Tyrone'),
    ('Enniskillen', 'Fermanagh'),
    ('Londonderry', 'Londonderry'),
    ('Coleraine', 'Londonderry')
) AS city_county_mapping(city_name, county_name)
WHERE Counties.county_name = city_county_mapping.county_name
ON CONFLICT DO NOTHING;